### ISSUE TITLE
No Funciona para la 1.8.9

### ISSUE THREAD

**Issue by Niicolaxx** [oitsjustjose/TiCon-Addons#11]
cuando busco los items del mod no aparecen los toolkits

**Comment by oitsjustjose** [comment]
Para 1.8.9, los toolkits fueron llamados "Bonus Modifiers". Y, por favor, mi Español solo es... _asi asi_ - si puedes, enviar otros informes in Ingles 😄

**Comment by Niicolaxx** [comment]
What is the name of the item to repair?
