### ISSUE TITLE
[1.12] Requires newer mod versions which don't even exist

### ISSUE THREAD

**Issue by BlazingV** [oitsjustjose/TiCon-Addons#13]
The mod requires _Tinkers' Construct **2.8.0.5**_ while the latest version (on Curse currently) is 2.7.2.19. And it also wants the newest and non-existent _Mantle **1.3.1.19**_.

**Screenshots:**

Error
![image](https://user-images.githubusercontent.com/16764953/29294358-e7e38ec2-8146-11e7-94b4-cef2ce8058e4.png)

Newest TConstruct version
![image](https://user-images.githubusercontent.com/16764953/29294385-079a81e4-8147-11e7-9f3e-40af083b6873.png)

Newest Mantle version
![image](https://user-images.githubusercontent.com/16764953/29294411-1d4f0c8a-8147-11e7-8c18-81a3ed6d7222.png)

**Comment by oitsjustjose** [comment]
Crap, was relying on Jenkins' latest release and not CurseForge's. Fixed, re-uploading. Thanks!
