### ISSUE TITLE
Crash with newest Tinkers

### ISSUE THREAD

**Issue by TheSnowyChickens** [oitsjustjose/TiCon-Addons#14]
Hello

There is the Crash log : https://pastebin.com/381NzxsN

I read your name in the log , so I think its a bug from your side :)

Thx

-I use :
1.12.1-forge1.12.1-14.22.0.2469
Mantle-1.12-1.3.1.21
TConstruct-1.12-2.7.3.30

**Comment by oitsjustjose** [comment]
Yup, the new version has been out for two hours so I guess that's long enough for me to expect this.

I'll fix it when I can.

**Comment by TheSnowyChickens** [comment]
You have all the time that you need.
Thx

**Comment by oitsjustjose** [comment]
Fixed c:
