### ISSUE TITLE
Auto-repair condition for daytime can never occur after the first day

### ISSUE THREAD

**Issue by esotericist** [oitsjustjose/TiCon-Addons#16]
Over here:

https://github.com/oitsjustjose/TiCon-Addons/blob/master/src/main/java/com/oitsjustjose/tinkers_addons/modifiers/ModAutoRepair.java#L94

you check world.getWorldTime(), which is the absolute time since the world started (so it also effectively encodes the moon phase and what often gets used as a basis for 'date' in some mods). It needs to be % 24000 in order to get the time value within a given day.

While I'm here, is it actually intended that your auto-repair works fastest in the nether?

**Comment by oitsjustjose** [comment]
Thanks, fixed :D

Also yes, it is intended; that's how it worked in TiCon 1. I don't know why, but I wanted to keep relatively original. 

¯\_(ツ)_/¯

**Comment by esotericist** [comment]
Fair enough. :D
