### ISSUE TITLE
Block progress reset on repair tick

### ISSUE THREAD

**Issue by Ozzymud** [oitsjustjose/TiCon-Addons#2]
Version: 1.0.1
Forge: 12.17.0.1965

When mining a block and the repair happens during, the progress on mining said block is reset.

**Comment by Ozzymud** [comment]
I never noticed it in 1.7.10, it gets me every few blocks

**Comment by Ozzymud** [comment]
Just made a 1.7.10 pack with only tinkers in it. Created an obsidian level pick and used it for a while to get the durability down to like 400/700. I then placed a lot of obsidian on the grund, added a single moss and silky to it(to slow the mining speed to 5). I then proceeded to break the obsidian blocks (took about 12 seconds each), I broke 20 obsidian blocks without the progress resetting a single time.

Back in my 1.9.4 world with a mining speed 6 pick on 20 obsidian, it reset progress on me over 10 times. While some type of reflection code might not have been used in Tinkers' 1.7 to check if a player is actively destroying a block, and it may indeed have reset progress at times, it still remains a not obvious or annoying thing in 1.7.10. This auto repair makes mining blocks that take over a second an exercise in frustration.

**Comment by oitsjustjose** [comment]
Alright, I've got this fixed, I'll release an update for all MC versions tomorrow :)

**Comment by oitsjustjose** [comment]
Just kidding. I've got releases out for all 3 MC versions now, currently being processed on CurseForge :)

**Comment by Ozzymud** [comment]
Haha, good job.. && !player.isSwingInProgress ... seems simple enough :)
