### ISSUE TITLE
Mossy stone bricks -> moss ball recipe

### ISSUE THREAD

**Issue by Ozzymud** [oitsjustjose/TiCon-Addons#3]
Version: 1.0.1
Forge: 12.17.0.1965

In 1.7.10 you could craft the moss ball from the smooth stone brick mossy blocks. Dunno if you are gonna leave it this way as that was a really easy way to obtain moss balls when mixed with the chisel mod as it could chisel smooth stone directly into mossy stone bricks.

**Comment by oitsjustjose** [comment]
I'll have to see what the current version of chisel does for mossy stone bricks and decide based on that. Of all things, CraftTweaker exists..
