### ISSUE TITLE
Server Side Crash - NoClassDefFoundError

### ISSUE THREAD

**Issue by JoelZBub** [oitsjustjose/TiCon-Addons#4]
Server crashes with Tinkers' Addons installed. 
 "NoClassDefFoundError: slimeknights/tconstruct/library/client/MaterialRenderInfo"

Attached is the crash report. 

Linux server 
Java 8
Forge 11.15.1.1902
[crash-2016-06-22_07.52.08-server.txt](https://github.com/oitsjustjose/TiCon-Addons/files/327734/crash-2016-06-22_07.52.08-server.txt)

**Comment by oitsjustjose** [comment]
Yup. I'll look into fixing this as soon as I can (today's a very busy day), but in the meantime you can disable the Thaumium Tool Material feature and that should resolve the issue. 

Sorry! Update soon hopefully :)

**Comment by JoelZBub** [comment]
Thanks for your attention to this. Your mod was highly requested by the players on my multiplayer modded server. They were a bit disappointed that I chose not to include this mod for the most recent update to the pack due to this bug. We're all looking forward to using it. Your mod and Bibliocraft are the top 2 on the list for a future update. :D

**Comment by oitsjustjose** [comment]
Fixed and uploaded to CurseForge - thanks for the report!

**Comment by JoelZBub** [comment]
Thank YOU! :D
