### ISSUE TITLE
Tinker's Addons 1.0.3 does NOT support 1.9.4

### ISSUE THREAD

**Issue by sblectric** [oitsjustjose/TiCon-Addons#5]
This error occured when running it on my server:

Encountered an unexpected exception
net.minecraftforge.fml.common.WrongMinecraftVersionException: Wrong Minecraft version for TinkersAddons

Wrong Minecraft Versions!

Mod: TinkersAddons

Location: /minecraft/servers/flux_universe/mods/Tinkers' Addons-1.10.x-1.0.3.jar

Expected: [1.10.2,1.10.2]

Current: Minecraft 1.9.4

**Comment by oitsjustjose** [comment]
Check curse in about 15 minutes for a new download. Same version number, just hot-fixed :)

**Comment by sblectric** [comment]
Cool, thanks for the quick response.

**Comment by oitsjustjose** [comment]
No problem, CurseForge is updated now!
