### ISSUE TITLE
Recipes not NBT sensitve

### ISSUE THREAD

**Issue by BloodWorkXGaming** [oitsjustjose/TiCon-Addons#9]
The Recipes are not nbt sensitive, meaning they show the right nbt in JEI, however you can use any plates made with any material to craft them.

To respect the nbt on the input items you have to implement your own IRecipe or extend ShapedRecipe.

Ran into this problem as well today, if you want I can make a PR to fix that issue.

**Comment by oitsjustjose** [comment]
Was this 1.10.2 or 1.11.2? I know in 1.10.2 they were working just fine, but I didn't think to check in 1.11.2

**Comment by BloodWorkXGaming** [comment]
It actually was 1.10 is was testing it in, ATM1 to be specific

**Comment by BloodWorkXGaming** [comment]
![image](https://user-images.githubusercontent.com/8137062/27332577-9aee794c-55c2-11e7-9a5e-ab8d64155e97.png)
Here for example, using 5 different plates

**Comment by BloodWorkXGaming** [comment]
You need to make a class like [this](https://github.com/AllTheMods/OreExcavationIntegration/blob/master/src/main/java/atm/bloodworkxgaming/oei/Crafting/NBTShapedRecipe.java)

and call it [like this](https://github.com/AllTheMods/OreExcavationIntegration/blob/master/src/main/java/atm/bloodworkxgaming/oei/Crafting/ModCrafting.java#L34)

**Comment by oitsjustjose** [comment]
Thanks! I was just about to work on a solution but this is marvelous. I just implemented it on the 1.11.2 branch (testing now before commit) - if it works, I'll backport it to 1.10.2 and try to update this morning before work.

**Comment by oitsjustjose** [comment]
Just updated 1.11.2 and 1.10.2 versions on [CurseForge](https://minecraft.curseforge.com/projects/tinkers-addons/files); hopefully they'll be up soon! Until then, if it's urgent you can use these:

[1.10.2](http://puu.sh/wpmgD/edda5e6bc8.jar)

[1.11.2](http://puu.sh/wpmgY/4d3dda8ad0.jar)

**Comment by BloodWorkXGaming** [comment]
Cool! It's all good, gonna update ATM1 at some point later today, so I am in no hurry.
Thanks for the fix ^^
